# Generated by Django 4.1.3 on 2022-12-21 10:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("job_description", models.TextField()),
                ("job_location", models.CharField(max_length=100)),
                ("job_site", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=100)),
                ("joblisting_id", models.IntegerField(unique=True)),
                ("first_crawling_date", models.DateField()),
                ("last_crawling_date", models.DateField()),
                ("joblisting_url", models.TextField(max_length=400, unique=True)),
                ("html_code", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="KeyWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key_word", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_term", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_searcher.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("job_description", models.TextField(blank=True)),
                ("job_location", models.CharField(blank=True, max_length=100)),
                ("job_site", models.CharField(blank=True, max_length=50)),
                ("joblisting_id", models.IntegerField(blank=True)),
                ("job_title", models.CharField(blank=True, max_length=100)),
                ("first_crawling_date", models.DateField(blank=True)),
                ("last_crawling_date", models.DateField(blank=True)),
                ("joblisting_url", models.TextField(blank=True, max_length=400)),
                ("html_code", models.TextField(blank=True)),
                (
                    "key_word",
                    models.ManyToManyField(blank=True, to="job_searcher.keyword"),
                ),
                (
                    "search_terms",
                    models.ManyToManyField(blank=True, to="job_searcher.searchterm"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="key_word",
            field=models.ManyToManyField(to="job_searcher.keyword"),
        ),
        migrations.AddField(
            model_name="job",
            name="search_terms",
            field=models.ManyToManyField(to="job_searcher.searchterm"),
        ),
    ]
