# Generated by Django 4.1.3 on 2022-12-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_searcher", "0003_alter_job_joblisting_id_alter_job_key_word_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawjob",
            name="company",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="first_crawling_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="html_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="is_active",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="job_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="job_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="job_site",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="job_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="joblisting_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="joblisting_url",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="last_crawling_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
