# Generated by Django 4.1.3 on 2022-12-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_searcher", "0005_alter_rawjob_joblisting_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawjob",
            name="joblisting_url",
            field=models.TextField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
