# Generated by Django 4.1.4 on 2022-12-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_searcher", "0007_alter_job_job_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job", old_name="key_word", new_name="key_words",
        ),
        migrations.RenameField(
            model_name="rawjob", old_name="key_word", new_name="key_words",
        ),
    ]
