# Generated by Django 4.1.4 on 2022-12-22 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_searcher", "0010_userrequests"),
    ]

    operations = [
        migrations.RenameModel(old_name="UserRequests", new_name="UserRequest",),
    ]
