# Generated by Django 4.1.4 on 2022-12-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_searcher", "0011_rename_userrequests_userrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrequest",
            name="key_words",
            field=models.ManyToManyField(to="job_searcher.keyword"),
        ),
    ]
