# Generated by Django 4.1.4 on 2022-12-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_searcher", "0012_alter_userrequest_key_words"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="joblisting_id",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="joblisting_url",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="joblisting_id",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="rawjob",
            name="joblisting_url",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
