# Generated by Django 4.1.4 on 2023-01-07 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_searcher', '0013_alter_job_joblisting_id_alter_job_joblisting_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
